# Generated by Django 4.0.1 on 2022-01-16 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_keys_values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='chave',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Apenas palavras MAIÚSCULAS são permitidas.')]),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='palavra',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Apenas palavras MAIÚSCULAS são permitidas.')]),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='palavra_encriptada',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
